### PR TITLE
feat: update material icons to fluent style

### PR DESCRIPTION
**Pull request by Xurdejl**
### Changes

- Replaced existing material icons with fluent-style icons for a more modern look
- Renamed some icons to maintain naming consistency
- Added a new volume icon to represent levels between 25% and 75%

preview_fluent_icons

Since the font file contains many different icons, here are some alternatives:

**Non filled middle button icons**
```
	play = "\239\152\133",
	pause = "\239\150\163",
	replay = "\238\189\191",
	previous = "\239\152\168",
	next = "\239\149\169",
	rewind = "\239\153\180",
	forward = "\239\143\190",
```

**Conventional full screen icon**
```
	fullscreen = "\238\154\132"
	fullscreen_exit = "\238\154\135"
```

### CODE REVIEW

**Comment by Xurdejl** [comment]
**Note:** I wanted to share a helpful resource for converting Unicode characters to the format used for icons in the osc.
[Browserling Unicode to Decimal Converter](https://www.browserling.com/tools/text-to-decimal). Additionally, you can open the `(change output format)` dropdown menu to change it to escaping characters like `\%d`

**Comment by Samillion** [comment]
> **Note:** I wanted to share a helpful resource for converting Unicode characters to the format used for icons in the osc. [Browserling Unicode to Decimal Converter](https://www.browserling.com/tools/text-to-decimal). Additionally, you can open the `(change output format)` dropdown menu to change it to escaping characters like `\%d`

I was just scratching my head over that. I usually use: 
```lua
-- lua
local glyph = ""
for i = 1, #glyph do
    print(string.byte(glyph, i))
end
```

Because I was trying to change the screenshot icon to a conventional one, but it's showing the wrong icon. Did the same on the website you linked, same unicode, but shows a different icon.

**I'll give you my notes, to see if you agree:**
- The screenshot button is too modern, does that make sense? Many people will not understand that this is "capture mode". We'll definitely get complaints of "I thought that was the full screen button" lol. A conventional one like `U+E719` would suffice.
- The middle buttons should be filled because they're a main focus, don't you think? Similar to your screenshot on your mpv conf repo. They look perfect. (play/pause/chapter/next/prev)
- The replay button is awesome, keep it as is
- The playlist button, I've seen people complain in old forks that it shows a "music note" lol. That is why I decided to go with the conventional look `U+E85F` in Fluent Icon. (I think that's why even on frontends they use that style)

I would do this myself, but for the life of me I'm unable to get the correct unicode to show the icon, not sure why. I tried your list of filled icons, but they're the same I think as the ones already in the PR.

Let me know what you think about my notes, please.

**Comment by Xurdejl** [comment]
> The screenshot button is too modern, does that make sense? Many people will not understand that this is "capture mode". We'll definitely get complaints of "I thought that was the full screen button" lol. A conventional one like U+E719 would suffice.

There is also `U+EA77` which is the screenshot button used in Microsoft Edge. Maybe people are familiarised with that one?

<br>

> The middle buttons should be filled because they're a main focus, don't you think? Similar to your screenshot on your mpv conf repo. They look perfect. (play/pause/chapter/next/prev)

Sure, I will use the filled ones

<br>

> The playlist button, I've seen people complain in old forks that it shows a "music note" lol. That is why I decided to go with the conventional look U+E85F in Fluent Icon. (I think that's why even on frontends they use that style)

Seems fair, let me change that one too

**Comment by Samillion** [comment]
> There is also U+EA77 which is the screenshot button used in Microsoft Edge. Maybe people are familiarised with that one?

Yeah. To be honest, any icon that is most recognized in most platforms would suffice. The "landscape" one is still dominating, not sure why lol.

> Sure, I will use the filled ones

Awesome. The fluent font has such a large collection compared to the 2022 Material.

**Comment by Xurdejl** [comment]
This is how it's looking now. Let me know if you'd like any other changes ^-^. Also, feel free to squash the commits if you want.

image

**Comment by Samillion** [comment]
Awesome! I've edited it to allow both fluent and material icon styles. Awesome work, man. Now users have all the choices they could ever want.

**Comment by Xurdejl** [comment]
> Awesome! I've edited it to allow both fluent and material icon styles. Awesome work, man. Now users have all the choices they could ever want.

Then I might update the material icons with the new material symbol font in the future

**Comment by Samillion** [comment]
I think I'll just keep fluent.

The implementation of both icon sets has proven to be a bit annoying. adjusting icon_style in modernz.conf is ignored.

Even if I apply the same logic that has been done with osc_styles and texts, still ignored.

I'm assuming it requires a re-init. That in itself makes the idea redundant.

Still tinkering around with it.

**Comment by Samillion** [comment]
**Note:** 
- I've changed the screenshot icon, I'll try to edit the one you used to match the size/height of the icons next to it later. It looked a bit off.
- I've updated the main repo with new reviews, font reference, and font credit to you and Fluent Systems.

**Comment by Xurdejl** [comment]
> **Note:**
> 
> * I've changed the screenshot icon, I'll try to edit the one you used to match the size/height of the icons next to it later. It looked a bit off.
> * I've updated the main repo with new reviews, font reference, and font credit to you and Fluent Systems.

Yes, don't worry, and thanks for the credits >_<.

<br>

Speaking of fluent design, I came across a Fluent colour palette that might be helpful:

_image

**Comment by Samillion** [comment]
Oh, you mean to use in a preset theme mode?
```lua
-- available presets: white, fluent, dracula, custom...etc
theme = "white", 
```

**Comment by Xurdejl** [comment]
> Oh, you mean to use in a preset theme mode?
> 
> ```lua
> -- available presets: white, fluent, dracula, custom...etc
> theme = "white", 
> ```

i meant in general in case we need to use colour somewhere

**Comment by Samillion** [comment]
What do you think about this for the screenshot icon? Does it fit? I'm not entirely sure. I didn't want to update without consulting you first.

image

**Comment by Xurdejl** [comment]
Seems straightforward and recognizable

**Pull request merged**
