### PR TITLE
feat: add dedicated layout for image mode

### PR DESCRIPTION
**Pull request by Samillion**
Pinging @Commander07 

Pinging @Xurdejl and @Keith94 as well.

Terribly sorry for the bother. Only if you can, could you help me test this please?

This is a restructure of https://github.com/Samillion/ModernZ/pull/158

**Now there are two layouts:**
- `modern`
- `modern-image`

**Handled with:**
```lua
    -- load layout
    is_image() -- init check if it's an image file
    if state.is_image then
        layouts["modern-image"]()
    else
        layouts["modern"]()
    end
```

**The `is_image()` function determines if the file is an image or not:**
```lua
local function is_image()
    local current_track = mp.get_property_native("current-tracks/video")
    if current_track and current_track.image and not current_track.albumart 
       and mp.get_property_number("estimated-frame-count", 0) < 2 and audio_track_count == 0 then
        state.is_image = true
    else
        state.is_image = false
    end
end
```

**Test script:** [/dev_imagemode_layout/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_imagemode_layout/modernz.lua)

### CODE REVIEW

**Comment by Xurdejl** [comment]
Love the new layout for images, looks so clean and works perfectly

**Comment by Samillion** [comment]
To do:
- Refactor element visibility in layout not in osc init
- Refactor title maxchars/clip in `modern-image` layout (base it on image width?)

**Comment by Commander07** [comment]
I don't think loop and screenshot buttons should be included in the image layout. As images have no need to be looped and unless the image is non-local then you have no need for a screenshot button. And in the case of a non-local image you really should download the image not screenshot it.

**Comment by Samillion** [comment]
Fully agreed.

**Comment by Keith94** [comment]
Looks very nice. 👍

A tiny bit glitchy when advancing to next/previous image in a playlist (the full OSC pops up for a few frames)

**Comment by Samillion** [comment]
> A tiny bit glitchy when advancing to next/previous image in a playlist (the full OSC pops up for a few frames)

Yeah, I've noticed that as well.

Once I get all the elements working correctly, and making sure that the regular layout wasn't affected by this change, I'll start addressing that issue.

**Comment by Keith94** [comment]
I want to apply `keep-open=always` for just images. Can I do that in auto profiles?

**Comment by Samillion** [comment]
Yup yup. I'll post an example auto-profile soon.

**Comment by Samillion** [comment]
OSC height should be decreased in modern-image, right? Since it holds less elements vertically.

**Comment by Keith94** [comment]
Ya, should be decreased.

**Comment by Keith94** [comment]
>A tiny bit glitchy when advancing to next/previous image

Now it looks OK after applying [ab1a762](https://github.com/Samillion/ModernZ/pull/163/commits/ab1a762a5dda16d69b8ffe5528cdaeac9c328255)

**Comment by Xurdejl** [comment]
> I want to apply `keep-open=always` for just images. Can I do that in auto profiles?

This should do the work
``` ini
[image-files]
profile-cond=filename:match("%.avif$") or filename:match("%.bmp$") or filename:match("%.gif$") or filename:match("%.j2k$") or filename:match("%.jp2$") or filename:match("%.jpeg$") or filename:match("%.jpg$") or filename:match("%.jxl$") or filename:match("%.png$") or filename:match("%.svg$") or filename:match("%.tga$") or filename:match("%.tif$") or filename:match("%.tiff$") or filename:match("%.webp$")
image-display-duration=inf
```

**Comment by Keith94** [comment]
@Xurdejl Nice. That's even better. Somehow I missed `image-display-duration` in the docs lol. Thanks!

**Comment by Commander07** [comment]
> > I want to apply `keep-open=always` for just images. Can I do that in auto profiles?
> 
> This should do the work
> 
> ```ini
> [image-files]
> profile-cond=filename:match("%.avif$") or filename:match("%.bmp$") or filename:match("%.gif$") or filename:match("%.j2k$") or filename:match("%.jp2$") or filename:match("%.jpeg$") or filename:match("%.jpg$") or filename:match("%.jxl$") or filename:match("%.png$") or filename:match("%.svg$") or filename:match("%.tga$") or filename:match("%.tif$") or filename:match("%.tiff$") or filename:match("%.webp$")
> image-display-duration=inf
> ```

There is no need for an auto profile for this as `image-display-duration` should only apply to images and can be include in your normal `mpv.conf`.

**Comment by Xurdejl** [comment]
> There is no need for an auto profile for this as `image-display-duration` should only apply to images and can be include in your normal `mpv.conf`.
Yeah, I realised shortly after posting it and edited the comment just when I got your notification, great timing haha

**Pull request merged**
