### PR TITLE
refactor: modern-image layout title width and elements visibility

### PR DESCRIPTION
**Pull request by Samillion**
Pinging: @Commander07 @Keith94 @Xurdejl 

Ok, so I merged the main layouts, now focusing on improving the looks of things.

**Changes:**
- Title width should now be handled and displayed better with extremely long filenames
- Playlist button and skip buttons should have better visibility now

**To do:**
- Anything else?

Test script: [/dev_modernimage_refactor/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_modernimage_refactor/modernz.lua)

image

### CODE REVIEW

**Comment by Xurdejl** [comment]
The only thing I could say is that the title sometimes stretches when it's too long.

<br>

> **To do:**
> 
> * Anything else?

Not about the image layout, but I guess something similar could be done for GIFs. Since they don't have sound, all the left buttons except the playlist aren’t needed.

**Comment by Keith94** [comment]
What about having the next and previous buttons be aligned to the right side along with the other buttons?

**Comment by Samillion** [comment]
The only thing I could say is that the title sometimes stretches when it's too long.

Terribly sorry for the bother, could you give me an example of a filename? or a character count?

> What about having the next and previous buttons be aligned to the right side along with the other buttons?

Excuse my French, but that is a fuckin great idea! It will make dealing with the title so much easier lol

**Comment by Keith94** [comment]
Haha glad you agree. They honestly looked a little lonely floating by themselves.

**Comment by Xurdejl** [comment]
> Terribly sorry for the bother, could you give me an example of a filename? or a character count?

Sorry, I meant squeeze. I think there was an issue about that because it also happened in the video layout but can't seem to find it.

image

**Comment by Samillion** [comment]
Oh, that's intentional. It clips the area. In essence, it's like a counterpart to maxchars.

The title has a specific width, once it goes beyond that, we use ass tags to `\\clip`
https://github.com/Samillion/ModernZ/blob/077e64e9667e0fd7a16593a7aba6b52cb1f9b189/modernz.lua#L1631

It has a side effect that it will change font type, because mpv font is limited, so it picks whatever your OS can cover with. (Arial, Sans Serif...etc)

**Comment by Samillion** [comment]
Forgot to note, the clipping should look much better once I apply Keith's idea.

**Comment by Xurdejl** [comment]
Oh, then everything else looks perfect. The only idea I can think of is having zoom in/out on scroll wheel in the image mode.

**Comment by Keith94** [comment]
>zoom in/out on scroll wheel in the image mode.

There may be some scripts out in the wild that can achieve similar things like that? I didn't test but came across this report earlier.

https://github.com/occivink/mpv-image-viewer?tab=readme-ov-file#scripts

**Comment by Samillion** [comment]
Should be easily implemented within ModernZ without external links. I think. I hope lol.

Since technically we can just add zoom in/out buttons and have them apply the effect on click/scroll

**Comment by Xurdejl** [comment]
Yes, by default the keybinds are "alt +" and "alt -" for zooming in and out.

**Comment by Samillion** [comment]
image

**Comment by Samillion** [comment]
This is the auto-profile I'll be using for image viewer mode: (personal use)

```ini
[Image-View]
    profile-cond=p['current-tracks/video'] and p['current-tracks/video'].image and not p['current-tracks/video'].albumart
    osd-playing-msg=${media-title} ${?width:${width}x${height}}
    osd-playing-msg-duration=4000
    reset-on-next-file=video-zoom,panscan,video-unscaled
    prefetch-playlist=yes
    script-opts-append=modernz-title=${media-title} ${?width:${width}x${height}}
    script-opts-append=modernz-showwindowtitle=no
    script-opts-append=modernz-showplaylist=yes
    script-opts-append=modernz-downloadbutton=yes
    script-opts-append=modernz-fade_alpha=100
    script-opts-append=modernz-tick_delay=0.03
```

I'll include it in the docs later as an example, so that users know how to adjust both general mpv options and ModernZ specific options.

**How should I add the zoom in/out button?**
- Two buttons, one for in one for out?
- One button with multi-function?

**Comment by Samillion** [comment]
I'll merge, then I'll open an issue to discuss further elements for image viewer mode. To keep things organized between PRs.

**Pull request merged**
