### PR TITLE
feat: disable irrelevant elements for images

### PR DESCRIPTION
**Pull request by Commander07**
## Changes
- Disables irrelevant elements (play/pause, jump, loop, screenshot, seekbar and time display) for images.
- Removes hover effects from disabled sliders to match button behavior.
- Adds `hide_elements_for_image` which when enabled will hide irrelevant elements for images

### CODE REVIEW

**Comment by Samillion** [comment]
There is no freakin way. I was JUST talking to mpv maintainers about implementing this very same thing. 😆 

image

**Comment by Samillion** [comment]
I like your implementation of checking frame count. Mind if I hold on merging for a bit? In theory, you can check for image in a more accurate way, to ensure consistency.

I'm in a very lazy mood so sticking in bed for a while lol.

An example of why checking frame count only might be a problem: audio files with coverart. Having additional checks to `is_image` would prevent it, ie: `current-tracks/video/image`

**Comment by Samillion** [comment]
Leaving this as a note, alongside frame count.

```lua
local current_track = mp.get_property_native("current-tracks/video")
local is_image = current_track and current_track.image and not current_track.albumart and mp.get_property_native("estimated-frame-count", 0) < 2
```

**Comment by Commander07** [comment]
> I like your implementation of checking frame count. Mind if I hold on merging for a bit? In theory, you can check for image in a more accurate way, to ensure consistency.
> 
> I'm in a very lazy mood so sticking in bed for a while lol.
> 
> An example of why checking frame count only might be a problem: audio files with coverart. Having additional checks to `is_image` would prevent it, ie: `current-tracks/video/image`

There is a check for audio tracks in the `is_image` check which makes sure audio files don't trigger it. However more checks won't hurt. I don't have time to do that today, so I'll look into it tomorrow.

Side note: Should there be an option to hide the seekbar and the other non regular media controls (play/pause, next/prev, jump and fullscreen) instead of disabling/graying out them?

**Comment by Samillion** [comment]
> There is a check for audio tracks in the is_image check which makes sure audio files don't trigger it. However more checks won't hurt. I don't have time to do that today, so I'll look into it tomorrow.

Yeah, I noticed and edited my reply right before you replied lol.

> Side note: Should there be an option to hide the seekbar and the other non regular media controls (play/pause, next/prev, jump and fullscreen) instead of disabling/graying out them?

Definitely. For my use case, I'd only want the relevant buttons showing.

**Comment by Samillion** [comment]
I realize the additional checks might be an overkill, but it's worth testing to be honest. To bulletproof `is_image` state. So it's not a replacement for your check, it's addition to it.

I'll test more once I get the energy to out of bed.

**Comment by Samillion** [comment]
> Side note: Should there be an option to hide the seekbar and the other non regular media controls (play/pause, next/prev, jump and fullscreen) instead of disabling/graying out them?

Your side note made me realize a scenario. playlist track next/previous buttons should be forced to show, regardless of `user_opts.shownextprev`, and if `have_pl`, right?

I think out of all the media control buttons, those two are the only ones that would make sense to show them (if it's a playlist)

What do you think?

**Comment by Commander07** [comment]
> Your side note made me realize a scenario. playlist track next/previous buttons should be forced to show, regardless of `user_opts.shownextprev`, and if `have_pl`, right?
> 
> I think out of all the media control buttons, those two are the only ones that would make sense to show them (if it's a playlist)
> 
> What do you think?

Because the playlist button will show up regardless if next/prev is enabled, so i think it's safe to allow next/prev to be hidden along with the rest of the buttons.

Hiding enabled, next/prev enabled:
image

Hiding enabled, next/prev disabled:
image


I have also encountered a weird bug where the download button is not being shown when `showjump` and `showskip` are both true and I'm not sure whats causing it. Could you have a look and see if you can spot the issue?

**Comment by Samillion** [comment]
Absolutely beautiful work. Love the placement of title. Do long titles overlap the buttons?

> I have also encountered a weird bug where the download button is not being shown when showjump and showskip are both true and I'm not sure whats causing it. Could you have a look and see if you can spot the issue?

Download button only shows if it's a web video (ie: path is url)
https://github.com/Samillion/ModernZ/blob/c053c5540bfc3c60301fce4e1bd2ad5de0856ed8/modernz.lua#L1351-L1354

https://github.com/Samillion/ModernZ/blob/c053c5540bfc3c60301fce4e1bd2ad5de0856ed8/modernz.lua#L2175-L2178

**Comment by Samillion** [comment]
By the way, if the title does overlap, you can invoke `maxchars`, like so:
https://github.com/Samillion/ModernZ/blob/c053c5540bfc3c60301fce4e1bd2ad5de0856ed8/modernz.lua#L1528

**Comment by Commander07** [comment]
> > I have also encountered a weird bug where the download button is not being shown when showjump and showskip are both true and I'm not sure whats causing it. Could you have a look and see if you can spot the issue?
> 
> Download button only shows if it's a web video (ie: path is url)

Just tried it now and it works i must have accidentally tested on a local file.

Some clarifications on some perhaps unclear communication from me:
- When next/prev is enabled and there is no playlist they will be grayed out.
image
- Playlist button and next/prev can both be disabled
image

So unless there are any changes or additions i feel that this PR is complete and ready for testing so it can be merged.

**Comment by Samillion** [comment]
Great effort, thank you so much. Merging.

**Pull request merged**
