### PR TITLE
refactor: update title formatting

### PR DESCRIPTION
**Pull request by Keith94**
Makes it match osc.lua defaults.

### CODE REVIEW

**Comment by FreeTheTech101** [comment]
Any opinions on defaulting to `${media-title/no-ext}`? Assuming the file in question has a title set, there shouldn't be a difference, but in the event there isn't one and it falls back to the file name, omitting `.mkv` or `.flac` could keep things less cluttered. More so asking to see what everyones opinion is on it, not for any immediate changes.

**Comment by Keith94** [comment]
We used it before but it was removed due to a bug: https://github.com/Samillion/ModernZ/issues/30

Sam provided a workaround for that though.

**Comment by Samillion** [comment]
Awesome! Thank  you very much, I didn't even realize those notes weren't updated.

**Changes to your PR:**
- fix: value for `screenshot_flag`. should be `subtitles`, not `subs`
- fix: correctly close table row with `|` for the `language` option row
- refactor: default title to `${media-title}`. mpv relies on playlist positions because the stock OSC doesn't include native playlist button or tooltips. In ModernZ title would look cluttered with `[2/5] title`. Nevertheless, the user has the option to modify it to their liking.

**Comment by Keith94** [comment]
Thanks for the fix 😃

**Pull request merged**
